document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<title></title>");
document.writeln("		<script src=\'js/jquery.js\'></script>");
document.writeln("		");
document.writeln("		<style>");
document.writeln("			body,");
document.writeln("dl,");
document.writeln("dt,");
document.writeln("dd,");
document.writeln("ul,");
document.writeln("ol,");
document.writeln("li,");
document.writeln("h1,");
document.writeln("h2,");
document.writeln("h3,");
document.writeln("h4,");
document.writeln("h5,");
document.writeln("h6,");
document.writeln("pre,");
document.writeln("code,");
document.writeln("form,");
document.writeln("fieldset,");
document.writeln("legend,");
document.writeln("input,");
document.writeln("button,");
document.writeln("textarea,");
document.writeln("p,");
document.writeln("blockquote,");
document.writeln("th,");
document.writeln("td {");
document.writeln("	margin: 0;");
document.writeln("	padding: 0;");
document.writeln("}");
document.writeln("");
document.writeln("h1,");
document.writeln("h2,");
document.writeln("h3,");
document.writeln("h4,");
document.writeln("h5,");
document.writeln("h6 {");
document.writeln("	font-size: 100%;");
document.writeln("}");
document.writeln("");
document.writeln("ul,");
document.writeln("li {");
document.writeln("	list-style-type: none;");
document.writeln("	margin: 0;");
document.writeln("	padding: 0;");
document.writeln("}");
document.writeln("");
document.writeln("body {");
document.writeln("	background: #f9f9f9;");
document.writeln("	font: 12px/1.5 \'//5FAE//8F6F//96C5//9ED1\', Arial, HELVETICA;");
document.writeln("	min-width: 1200px;");
document.writeln("	_background-image: url(about:blank);");
document.writeln("	_background-attachment: fixed;");
document.writeln("}");
document.writeln("");
document.writeln("img {");
document.writeln("	border: 0;");
document.writeln("}");
document.writeln("");
document.writeln("ol,");
document.writeln("ul {");
document.writeln("	list-style: none;");
document.writeln("}");
document.writeln("");
document.writeln(":link,");
document.writeln(" :visited,");
document.writeln("ins {");
document.writeln("	text-decoration: none;");
document.writeln("}");
document.writeln("");
document.writeln("table {");
document.writeln("	border-collapse: collapse;");
document.writeln("	border-spacing: 0;");
document.writeln("}");
document.writeln("a{");
document.writeln("	cursor: pointer;");
document.writeln("}");
document.writeln("");
document.writeln("#first{");
document.writeln("	height:35px;");
document.writeln("	width:100%;");
document.writeln("	background-color: #eeeeee;");
document.writeln("");
document.writeln("	");
document.writeln("}");
document.writeln("#first .muyee_bg{");
document.writeln("	height: 35px;");
document.writeln("	width: 1100px;");
document.writeln("	margin: 0 auto;");
document.writeln("}");
document.writeln(".muyee_bg .muyee_left{");
document.writeln("	height:35px;");
document.writeln("	width:200px;");
document.writeln("");
document.writeln("	");
document.writeln("	float: left;");
document.writeln("	font-size: 13px;");
document.writeln("	line-height: 35px;");
document.writeln("	color:#999999;");
document.writeln("	margin: 0 auto;");
document.writeln("}");
document.writeln(".muyee_bg .muyee_right{");
document.writeln("");
document.writeln("	height:35px;");
document.writeln("	width:300px;");
document.writeln("	");
document.writeln("	float: right;");
document.writeln("	");
document.writeln("	line-height: 35px;");
document.writeln("	color:#999999;");
document.writeln("	");
document.writeln("		");
document.writeln("}");
document.writeln(".muyee_bg .muyee_right .m_c{");
document.writeln("	color:#999999;");
document.writeln("}");
document.writeln(".white_content {");
document.writeln("	border-radius:4px ;");
document.writeln("display: none;");
document.writeln("margin-top: -40px;");
document.writeln("position:fixed;");
document.writeln("top:250px;");
document.writeln("left:500px;");
document.writeln("width:17%;");
document.writeln("height:240px;");
document.writeln("margin-left:80px;");
document.writeln("border: 1px solid #E5E5E5;");
document.writeln("background-color: white;");
document.writeln("z-index:2002;");
document.writeln("overflow: auto;");
document.writeln("");
document.writeln("}");
document.writeln(".white_content img{");
document.writeln("	margin-top: 12px;");
document.writeln("   margin-left:25px;");
document.writeln("	height: 175px;");
document.writeln("	width:190px;");
document.writeln("	}");
document.writeln("	#second{");
document.writeln("		height: 55px;");
document.writeln("	width:100%;");
document.writeln("	}");
document.writeln("	#second .muyee_bg1{");
document.writeln("		height: 55px;");
document.writeln("	width: 1100px;");
document.writeln("	");
document.writeln("	margin: 0 auto;");
document.writeln("		}");
document.writeln("	#second .muyee_bg1 .muyee_logo{");
document.writeln("		height: 55px;");
document.writeln("		width: 300px;");
document.writeln("		float: left;");
document.writeln("	");
document.writeln("		line-height: 55px;");
document.writeln(" ");
document.writeln("		}");
document.writeln("		#second .muyee_bg1 .muyee_nav{");
document.writeln("		height: 55px;");
document.writeln("		width: 450px;");
document.writeln("		float: right;");
document.writeln("		}");
document.writeln("		#second .muyee_bg1 .muyee_nav ul li{");
document.writeln("			font-size: 15px;");
document.writeln("			font-weight:500;");
document.writeln("			width: 90px;");
document.writeln("			height: 55px;");
document.writeln("			line-height: 55px;");
document.writeln("			float: left;");
document.writeln("		");
document.writeln("			text-align: center;");
document.writeln("		");
document.writeln("		}");
document.writeln("	 .cur{");
document.writeln("	 	border-bottom:#ff5b1e solid ;");
document.writeln("	 	width: 10px;");
document.writeln("	 	border-width:1px ;");
document.writeln("			color: #ff5b1e;");
document.writeln("			}");
document.writeln("			.cur_bg:hover{");
document.writeln("				height:30px;");
document.writeln("				background-color: #ff5b1e;");
document.writeln("				color: white !important;");
document.writeln("				width: 50px;");
document.writeln("				");
document.writeln("			}");
document.writeln("		#second .muyee_bg1 .muyee_nav ul li:hover{");
document.writeln("			color: #ff5b1e;");
document.writeln("			cursor: pointer;");
document.writeln("			");
document.writeln("			}");
document.writeln("		");
document.writeln("		a, abbr, acronym, address, applet, article, aside, audio, b, big, blockquote, canvas, caption, center, cite, code, dd, del, details, dfn, dl, dt, em, embed, fieldset, figcaption, figure, footer, form, header, hgroup, html, i, iframe, img, ins, kbd, label, legend, li, mark, menu, nav, object, ol, output, p, pre, q, ruby, s, samp, section, small, span, strike, strong, sub, summary, sup, table, tbody, td, tfoot, th, thead, time, tr, tt, u, ul, var, video { margin: 0; padding: 0;");
document.writeln("");
document.writeln("	font-weight:inherit;");
document.writeln("	font-size: 12px;");
document.writeln("	vertical-align: baseline;");
document.writeln("	font-family:Microsoft YaHei,Hiragino Sans GB W3,PingFang-SC-Regular,Helvetica Neue,Helvetica,microsoft yahei,sans-serif;");
document.writeln("");
document.writeln("}");
document.writeln("");
document.writeln("ol, ul { list-style: none }");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("img { vertical-align: middle }");
document.writeln("a, button, div, em, i, input, li, p, section, span, ul { -webkit-tap-highlight-color: rgba(255,0,0,0); font-style: normal; list-style:none; }");
document.writeln("");
document.writeln("html,body { height: 100%; }");
document.writeln("");
document.writeln("input { background-color: #fff; font-size: 1em; outline:none; text-indent: 10px; }");
document.writeln("");
document.writeln("a:hover { opacity: 0.8; filter:alpha(opacity=80); text-decoration: blink }");
document.writeln(".clear {clear: both;}");
document.writeln("");
document.writeln("");
document.writeln("#place { background: url(img/dsfw.png) no-repeat 96% center; }");
document.writeln("");
document.writeln("");
document.writeln("#in_city { background: #ddd; position: absolute; z-index: 999;border: solid 1px #d7d7d7; background: #fff;padding-bottom: 6px; }");
document.writeln(".screen { overflow: hidden; }");
document.writeln(".screen a { float: left; color:#ff5b1e; padding: 1px 12.6px; text-align: center; border-bottom: solid 1px #c92436; }");
document.writeln(".screen a:hover { color: #c92436; }");
document.writeln(".screen .shar { color: #404040; border: solid 1px #c92436; border-bottom: none; }");
document.writeln(".city_a_le1 { padding: 10px; overflow: hidden; }");
document.writeln(".city_a_le1 a { float: left; width: 20%; margin: 2px 0; }");
document.writeln(".Letter span { width: 12%; float: left; text-align: center; padding: 2px 0; }");
document.writeln(".Letter div { width: 88%; float: left; }");
document.writeln(".city_a_le1 a:hover { color: #c92436; }");
document.writeln(".Letter div a { width: 25%; }");
document.writeln("#in_city h1 { padding: 10px 0; color: #ababab; text-indent: 3%; }");
document.writeln("input { border: solid 1px #e1e1e1; height: 25px; border-radius: 3px; text-indent: 10px;top:3px; width: 70px; position: relative; cursor: pointer;}");
document.writeln("");
document.writeln("");
document.writeln("		</style>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<div id=\'first\'>");
document.writeln("			<div class=\'muyee_bg\'>");
document.writeln("				<div class=\'muyee_left\'>");
document.writeln("					<p>贷款就上银时资产！&nbsp;400-890-2180</p>");
document.writeln("				</div>");
document.writeln("				<div class=\'muyee_right\'>");
document.writeln("					<p align=\'right\'>");
document.writeln("						<a href=\'\' target=\'_blank\' class=\'m_c\'>咨询</a>&nbsp;&nbsp;&nbsp;");
document.writeln("						<a href=\'\' target=\'_blank\' class=\'m_c\'>问答</a>&nbsp;&nbsp;&nbsp;");
document.writeln("						<a href=\'\' target=\'_blank\' class=\'m_c\'>登录</a>&nbsp;&nbsp;&nbsp;");
document.writeln("						<a href=\'\' target=\'_blank\' class=\'m_c\'>注册</a>&nbsp;&nbsp;&nbsp;");
document.writeln("						");
document.writeln("						<a onclick=\'ShowDiv(\'MyDiv\',\'fade\')\'><img src=\'img/header_phone.png\' style=\'margin-top: -2px; height: 20px;\'>&nbsp;手机</a>");
document.writeln("					</p>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<div id=\'MyDiv\' class=\'white_content\'>");
document.writeln("				<div style=\' cursor: default; height: 40px;font-size: 15px; background-color: #EEEEEE; line-height: 40px;\' id=\'move\'>");
document.writeln("					<span>&nbsp;&nbsp;扫一扫，轻松访问手机网页</span><span style=\'font-size: 16px; float: right;cursor: pointer;\' onclick=\'CloseDiv(\'MyDiv\',\'fade\')\'>X&nbsp;</span>");
document.writeln("");
document.writeln("				</div>");
document.writeln("				<img src=\'img/erweima.png\'>");
document.writeln("");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("");
document.writeln("		<!--");
document.writeln("        	头部电话 咨询 问答栏结束");
document.writeln("        -->");
document.writeln("");
document.writeln("		<!--");
document.writeln("             logo栏+定位栏 +导航栏");
document.writeln("        -->");
document.writeln("");
document.writeln("		<div id=\'second\'>");
document.writeln("			<div class=\'muyee_bg1\'>");
document.writeln("				<div class=\'muyee_logo\'>");
document.writeln("					<p><img src=\'img/logo.png\' width=\'150px\' height=\'30px\'>&nbsp;&nbsp;<img src=\'img/sx.PNG\' height=\'32px\' style=\'margin-bottom: -3px;\'>&nbsp;&nbsp;<label style=\'top: 3px; position: relative;font-size: 18px;color: #666666;\'>个人信息中心&nbsp;</label><!--<input type=\'text\' placeholder=\'全国\' id=\'place\' name=\'\'>--></p>");
document.writeln("				</div>");
document.writeln("				<div id=\'in_city\' style=\'display: none\'></div>");
document.writeln("				<div class=\'muyee_nav\'>");
document.writeln("					<ul>");
document.writeln("						<li class=\'cur\' ><a href=\'muyee_index.html\' style=\'color: #222222;\'>首页</a></li>");
document.writeln("						<li><a href=\'muyee_Loanindex.html\' style=\'color: #222222;\'>贷款</a></li>");
document.writeln("						<li><a href=\'muyee_Friendloan.html\' style=\'color: #222222;\'>合作伙伴</a></li>");
document.writeln("						<li><a href=\'muyee_Joinour.html\' style=\'color: #222222;\'> 加入我们</a></li>");
document.writeln("						<li class=\'cur_bg\'><a href=\'muyee_About.html\' style=\'color: #222222;\'>关于我们</a></li>");
document.writeln("						");
document.writeln("");
document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("	</body>");
document.writeln("	<script type=\'text/javascript\' src=\'js/cityTemplate.js\'></script>");
document.writeln("	<!--<script type=\'text/javascript\'>");
document.writeln("		var cityA = $(\'.city_a_le1 a\'); //城市");
document.writeln("		var pla = $(\'#place\'); //出发地");
document.writeln("		var dest = $(\'#destination\');");
document.writeln("		// 默认值");
document.writeln("		inCity.width = \'345\'; //城市选择框  宽");
document.writeln("		inCity.height = \'auto\'; //城市选择框  高");
document.writeln("		inCity.id = \'#in_city\'; //城市选择框  父级ID");
document.writeln("		inCity.Children = \'.city_a_le1\'; //城市名box");
document.writeln("		// 初始化 城市HTML模板");
document.writeln("		$(inCity.id).prepend(inCity._template.join(\'\'));");
document.writeln("		inCity.Hot(cityA);");
document.writeln("");
document.writeln("		//城市 导航");
document.writeln("		var apay = $(\'.screen a\');");
document.writeln("");
document.writeln("		var placeThis; //当前选择标签");
document.writeln("		apay.click(function(obj) { //城市导航");
document.writeln("			inCity.payment($(this));");
document.writeln("		})");
document.writeln("");
document.writeln("		inCity.place(pla); //当前城市");
document.writeln("		inCity.destination(dest); //选择");
document.writeln("		inCity.cityClick(cityA); //显示赋值城市");
document.writeln("	</script>-->");
document.writeln("	<script src=\'js/js.js\'></script>");
document.writeln("</html>");
document.writeln("");