document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<title></title>");
document.writeln("		<style>");
document.writeln("						body,");
document.writeln("dl,");
document.writeln("dt,");
document.writeln("dd,");
document.writeln("ul,");
document.writeln("ol,");
document.writeln("li,");
document.writeln("h1,");
document.writeln("h2,");
document.writeln("h3,");
document.writeln("h4,");
document.writeln("h5,");
document.writeln("h6,");
document.writeln("pre,");
document.writeln("code,");
document.writeln("form,");
document.writeln("fieldset,");
document.writeln("legend,");
document.writeln("input,");
document.writeln("button,");
document.writeln("textarea,");
document.writeln("p,");
document.writeln("blockquote,");
document.writeln("th,");
document.writeln("td {");
document.writeln("	margin: 0;");
document.writeln("	padding: 0;");
document.writeln("}");
document.writeln("");
document.writeln("h1,");
document.writeln("h2,");
document.writeln("h3,");
document.writeln("h4,");
document.writeln("h5,");
document.writeln("h6 {");
document.writeln("	font-size: 100%;");
document.writeln("}");
document.writeln("");
document.writeln("ul,");
document.writeln("li {");
document.writeln("	list-style-type: none;");
document.writeln("	margin: 0;");
document.writeln("	padding: 0;");
document.writeln("}");
document.writeln("");
document.writeln("body {");
document.writeln("	background: #f9f9f9;");
document.writeln("	font: 12px/1.5 \'\/\/5FAE\/\/8F6F\/\/96C5\/\/9ED1\', Arial, HELVETICA;");
document.writeln("	min-width: 1200px;");
document.writeln("	_background-image: url(about:blank);");
document.writeln("	_background-attachment: fixed;");
document.writeln("}");
document.writeln("");
document.writeln("img {");
document.writeln("	border: 0;");
document.writeln("}");
document.writeln("");
document.writeln("ol,");
document.writeln("ul {");
document.writeln("	list-style: none;");
document.writeln("}");
document.writeln("");
document.writeln(":link,");
document.writeln(" :visited,");
document.writeln("ins {");
document.writeln("	text-decoration: none;");
document.writeln("}");
document.writeln("");
document.writeln("table {");
document.writeln("	border-collapse: collapse;");
document.writeln("	border-spacing: 0;");
document.writeln("}");
document.writeln("a{");
document.writeln("	cursor: pointer;");
document.writeln("}");
document.writeln("");
document.writeln("			/**尾部*/");
document.writeln("#muyee_footer{");
document.writeln("	height: 320px;");
document.writeln("	width: 100%;");
document.writeln("	background-color: #E5E5E5;");
document.writeln("	");
document.writeln("");
document.writeln("}");
document.writeln("#muyee_footer .m_f{");
document.writeln("	height: 320px;");
document.writeln("	width: 1100px;");
document.writeln("	margin: 0 auto;");
document.writeln("");
document.writeln("}");
document.writeln("#muyee_footer .m_f .m1{");
document.writeln("	height: 180px;");
document.writeln("	width: 60px;");
document.writeln("	color: #666666;");
document.writeln("	line-height: 30px;");
document.writeln("	text-align: center;");
document.writeln("	float: left;");
document.writeln("	}");
document.writeln("#muyee_footer .m_f .m1 .current a{");
document.writeln("	color: #222222;");
document.writeln("	font-size: 14px;");
document.writeln("	}");
document.writeln("	#muyee_footer .m_f .m2{");
document.writeln("	height: 180px;");
document.writeln("	width: 80px;");
document.writeln("	margin-left: 40px;");
document.writeln("	text-align: center;");
document.writeln("	");
document.writeln("	color: #666666;");
document.writeln("	line-height: 30px;");
document.writeln("");
document.writeln("	float: left;");
document.writeln("	}");
document.writeln("	#muyee_footer .m_f .m2 .current a{");
document.writeln("	color: #222222;");
document.writeln("	font-size: 14px;");
document.writeln("	}");
document.writeln("	#muyee_footer .m_f .m3{");
document.writeln("	height: 180px;");
document.writeln("	width: 80px;");
document.writeln("	margin-left: 40px;");
document.writeln("	text-align: center;");
document.writeln("	");
document.writeln("	color: #666666;");
document.writeln("	line-height: 30px;");
document.writeln("");
document.writeln("	float: left;");
document.writeln("	}");
document.writeln("	#muyee_footer .m_f .m3 .current a{");
document.writeln("	color: #222222;");
document.writeln("	font-size: 14px;");
document.writeln("	}");
document.writeln("	#muyee_footer .m_f .m4{");
document.writeln("		margin-top: 10px;");
document.writeln("	height: 200px;");
document.writeln("	width: 200px;");
document.writeln("	margin-left:130px;");
document.writeln("	text-align: center;");
document.writeln("	");
document.writeln("	color: #666666;");
document.writeln("	line-height: 30px;");
document.writeln("");
document.writeln("	float: left;");
document.writeln("	}");
document.writeln("	#muyee_footer .m_f .m4 img{");
document.writeln("		width:200px;");
document.writeln("		height:180px;");
document.writeln("	");
document.writeln("	}");
document.writeln("	#muyee_footer .m_f .m5{");
document.writeln("	height: 230px;");
document.writeln("	width: 410px;");
document.writeln("");
document.writeln("margin-top: 5px;");
document.writeln("	float: right;");
document.writeln("	}");
document.writeln("	#muyee_footer .m_f .m5 .m5_a{");
document.writeln("		float: left;");
document.writeln("		height: 40px;");
document.writeln("		width: 40px;");
document.writeln("		");
document.writeln("		}");
document.writeln("	#muyee_footer .m_f .m5 .m5_a img{");
document.writeln("		width: 100%;");
document.writeln("		margin-top:5px;");
document.writeln("		}");
document.writeln("		#muyee_footer .m_f .m5  ul li{");
document.writeln("		line-height: 25px;");
document.writeln("		color: #666666;");
document.writeln("		");
document.writeln("		}");
document.writeln("		");
document.writeln("			#muyee_footer .m_f .m5 .m5_b{");
document.writeln("		float: left;");
document.writeln("		height: 40px;");
document.writeln("		width: 200px;");
document.writeln("		");
document.writeln("		}");
document.writeln("		#muyee_footer .m_f .m_ft{");
document.writeln("			width: 700px;");
document.writeln("			height: 70px;");
document.writeln("			margin: 0 auto;");
document.writeln("			");
document.writeln("		}");
document.writeln("		#muyee_footer .m_f .m_ft img{");
document.writeln("			margin-left: 15px;");
document.writeln("			width: 17%;");
document.writeln("			}");
document.writeln("		");
document.writeln("		</style>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<!--");
document.writeln("        尾部");
document.writeln("        -->");
document.writeln("        <div id=\'muyee_footer\'>");
document.writeln("        	<div class=\'m_f\'>");
document.writeln("        		<div class=\'m1\'><ul><li class=\'current\'><a href=\'muyee_About.html\'>关于我们</a></li><li><a href=\'muyee_About.html\' style=\'color: #222222;\'>公司介绍</a></li><li><a href=\'muyee_About.html\' style=\'color: #222222;\'>公司文化</a></li><li><a href=\'muyee_About.html\' style=\'color: #222222;\'>企业文化</a></li><li><a>联系我们</a></li></ul></div>");
document.writeln("        		<div class=\'m2\'><ul><li class=\'current\'><a href=\'muyee_Friendloan.html\'>商家合作</a></li><li><a href=\'muyee_Friendloan.html\' style=\'color: #666666;\'>贷款商家合作</a></li><li><a style=\'color: #666666;\' href=\'muyee_Friendloan.html\'>中介合作</a></li></ul></div>");
document.writeln("        		<div class=\'m3\'><ul><li class=\'current\'><a>贷款指南</a></li><li><a>如何办理贷款</a></li><li><a>咨询相关问题</a></li><li><a>贷款主要事项</a></li><li><a>其他问题</a></li></ul></div>");
document.writeln("        		<div class=\'m4\'>");
document.writeln("        			<p align=\'center\'>扫一扫，关注我们</p>");
document.writeln("        			<p  align=\'center\'><img src=\'img/qrcodeMap.jpg\'></p> ");
document.writeln("        		</div>");
document.writeln("        		");
document.writeln("        		<div class=\'m5\'>");
document.writeln("        			<div class=\'m5_a\'><img src=\'img/header_phone.png\'></div>");
document.writeln("        			<div class=\'m5_b\'>");
document.writeln("        				<p style=\'color: #666666;\'>客服热线（工作时间 8:00-22:00）</p>");
document.writeln("        				<p style=\'font-size: 27px; color: #999999;\'>400-890-2180 </p>");
document.writeln("        			</div>");
document.writeln("        			<div style=\'clear: both;\'></div>");
document.writeln("        			<br />");
document.writeln("        			<ul>");
document.writeln("        			<li class=\'jg\'>广东省东莞市南城街道莞太路111号民间金融大厦2号楼505</li>");
document.writeln("        			");
document.writeln("        			<li class=\'jg\'>邮政编码：523000</li>");
document.writeln("        		</ul>");
document.writeln("        		</div>");
document.writeln("        		<div style=\'clear: both;\'></div>");
document.writeln("        		<div class=\'m_ft\'>");
document.writeln("        			<p><img src=\'img/f1.PNG\'>&nbsp;<img src=\'img/f2.PNG\'>&nbsp;<img src=\'img/f3.PNG\'>&nbsp;<img src=\'img/f4.PNG\'>&nbsp;<img src=\'img/f5.PNG\'></p>");
document.writeln("        		");
document.writeln("        		<p align=\'center\'>经营许可证号:<a href=\'http://www.miit.gov.cn/\' style=\'color: #666666;\'>粤ICP备17082633号-1</a>  Powered by biyin 1.0 </p>");
document.writeln("        		</div>");
document.writeln("        	</div>");
document.writeln("        	");
document.writeln("        </div>");
document.writeln("        <!--");
document.writeln("        	结束尾部");
document.writeln("        -->");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");