document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<title></title>");
document.writeln("		");
document.writeln("		");
document.writeln("		<style>");
document.writeln("			body,");
document.writeln("dl,");
document.writeln("dt,");
document.writeln("dd,");
document.writeln("ul,");
document.writeln("ol,");
document.writeln("li,");
document.writeln("h1,");
document.writeln("h2,");
document.writeln("h3,");
document.writeln("h4,");
document.writeln("h5,");
document.writeln("h6,");
document.writeln("pre,");
document.writeln("code,");
document.writeln("form,");
document.writeln("fieldset,");
document.writeln("legend,");
document.writeln("input,");
document.writeln("button,");
document.writeln("textarea,");
document.writeln("p,");
document.writeln("blockquote,");
document.writeln("th,");
document.writeln("td {");
document.writeln("	margin: 0;");
document.writeln("	padding: 0;");
document.writeln("}");
document.writeln("");
document.writeln("h1,");
document.writeln("h2,");
document.writeln("h3,");
document.writeln("h4,");
document.writeln("h5,");
document.writeln("h6 {");
document.writeln("	font-size: 100%;");
document.writeln("}");
document.writeln("");
document.writeln("ul,");
document.writeln("li {");
document.writeln("	list-style-type: none;");
document.writeln("	margin: 0;");
document.writeln("	padding: 0;");
document.writeln("}");
document.writeln("");
document.writeln("body {");
document.writeln("	background: #f9f9f9;");
document.writeln("	font: 12px/1.5 \'//5FAE//8F6F//96C5//9ED1\', Arial, HELVETICA;");
document.writeln("	min-width: 1200px;");
document.writeln("	_background-image: url(about:blank);");
document.writeln("	_background-attachment: fixed;");
document.writeln("}");
document.writeln("");
document.writeln("img {");
document.writeln("	border: 0;");
document.writeln("}");
document.writeln("");
document.writeln("ol,");
document.writeln("ul {");
document.writeln("	list-style: none;");
document.writeln("}");
document.writeln("");
document.writeln(":link,");
document.writeln(" :visited,");
document.writeln("ins {");
document.writeln("	text-decoration: none;");
document.writeln("}");
document.writeln("");
document.writeln("table {");
document.writeln("	border-collapse: collapse;");
document.writeln("	border-spacing: 0;");
document.writeln("}");
document.writeln("a{");
document.writeln("	cursor: pointer;");
document.writeln("}");
document.writeln("");
document.writeln("#first{");
document.writeln("	height:35px;");
document.writeln("	width:100%;");
document.writeln("	background-color: #eeeeee;");
document.writeln("");
document.writeln("	");
document.writeln("}");
document.writeln("#first .muyee_bg{");
document.writeln("	height: 35px;");
document.writeln("	width: 1100px;");
document.writeln("	margin: 0 auto;");
document.writeln("}");
document.writeln(".muyee_bg .muyee_left{");
document.writeln("	height:35px;");
document.writeln("	width:200px;");
document.writeln("");
document.writeln("	");
document.writeln("	float: left;");
document.writeln("	font-size: 13px;");
document.writeln("	line-height: 35px;");
document.writeln("	color:#999999;");
document.writeln("	margin: 0 auto;");
document.writeln("}");
document.writeln(".muyee_bg .muyee_right{");
document.writeln("");
document.writeln("	height:35px;");
document.writeln("	width:300px;");
document.writeln("	");
document.writeln("	float: right;");
document.writeln("	");
document.writeln("	line-height: 35px;");
document.writeln("	color:#999999;");
document.writeln("	");
document.writeln("		");
document.writeln("}");
document.writeln(".muyee_bg .muyee_right .m_c{");
document.writeln("	color:#999999;");
document.writeln("}");
document.writeln(".white_content {");
document.writeln("	border-radius:4px ;");
document.writeln("display: none;");
document.writeln("margin-top: -40px;");
document.writeln("position:fixed;");
document.writeln("top:250px;");
document.writeln("left:500px;");
document.writeln("width:17%;");
document.writeln("height:240px;");
document.writeln("margin-left:80px;");
document.writeln("border: 1px solid #E5E5E5;");
document.writeln("background-color: white;");
document.writeln("z-index:2002;");
document.writeln("overflow: auto;");
document.writeln("");
document.writeln("}");
document.writeln(".white_content img{");
document.writeln("	margin-top: 12px;");
document.writeln("   margin-left:25px;");
document.writeln("	height: 175px;");
document.writeln("	width:190px;");
document.writeln("	}");
document.writeln("	");
document.writeln("		");
document.writeln("		a, abbr, acronym, address, applet, article, aside, audio, b, big, blockquote, canvas, caption, center, cite, code, dd, del, details, dfn, dl, dt, em, embed, fieldset, figcaption, figure, footer, form, header, hgroup, html, i, iframe, img, ins, kbd, label, legend, li, mark, menu, nav, object, ol, output, p, pre, q, ruby, s, samp, section, small, span, strike, strong, sub, summary, sup, table, tbody, td, tfoot, th, thead, time, tr, tt, u, ul, var, video { margin: 0; padding: 0;");
document.writeln("");
document.writeln("	font-weight:inherit;");
document.writeln("	font-size: 12px;");
document.writeln("	vertical-align: baseline;");
document.writeln("	font-family:Microsoft YaHei,Hiragino Sans GB W3,PingFang-SC-Regular,Helvetica Neue,Helvetica,microsoft yahei,sans-serif;");
document.writeln("");
document.writeln("}");
document.writeln("");
document.writeln("ol, ul { list-style: none }");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("img { vertical-align: middle }");
document.writeln("a, button, div, em, i, input, li, p, section, span, ul { -webkit-tap-highlight-color: rgba(255,0,0,0); font-style: normal; list-style:none; }");
document.writeln("");
document.writeln("html,body { height: 100%; }");
document.writeln("");
document.writeln("input { background-color: #fff; font-size: 1em; outline:none; text-indent: 10px; }");
document.writeln("");
document.writeln("a:hover { opacity: 0.8; filter:alpha(opacity=80); text-decoration: blink }");
document.writeln(".clear {clear: both;}");
document.writeln("");
document.writeln("");
document.writeln("#place { background: url(img/dsfw.png) no-repeat 96% center; }");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		</style>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<div id=\'first\'>");
document.writeln("			<div class=\'muyee_bg\'>");
document.writeln("				<div class=\'muyee_left\'>");
document.writeln("					<p>贷款就上比银网！</p>");
document.writeln("				</div>");
document.writeln("				<div class=\'muyee_right\'>");
document.writeln("					<p align=\'right\'>");
document.writeln("						<a href=\'\' target=\'_blank\' class=\'m_c\'>咨询</a>&nbsp;&nbsp;&nbsp;");
document.writeln("						<a href=\'\' target=\'_blank\' class=\'m_c\'>问答</a>&nbsp;&nbsp;&nbsp;");
document.writeln("						<a href=\'muyee_Login.html\' target=\'_blank\' class=\'m_c\'>登录</a>&nbsp;&nbsp;&nbsp;");
document.writeln("						<a href=\'muyee_Sinup.html\' target=\'_blank\' class=\'m_c\'>注册</a>&nbsp;&nbsp;&nbsp;");
document.writeln("						");
document.writeln("						<a onclick=\'ShowDiv(\'MyDiv\',\'fade\')\'><img src=\'img/header_phone.png\' style=\'margin-top: -2px; height: 20px;\'>&nbsp;手机</a>");
document.writeln("					</p>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			");
document.writeln("		<!--");
document.writeln("        	头部电话 咨询 问答栏结束");
document.writeln("        -->");
document.writeln("");
document.writeln("		");
document.writeln("		");
document.writeln("		</div>");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("	</body>");
document.writeln("	");
document.writeln("	");
document.writeln("");
document.writeln("</html>");
document.writeln("");